version: '3.8'

services:
  vietnam-hearts:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vietnam-hearts-container
    ports:
      - "8080:8080"
    environment:
      - ENVIRONMENT=development
      - PORT=8080
      - API_URL=http://localhost:8080
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
      - ./secrets:/app/secrets
      - ./templates:/app/templates
    networks:
      - vietnam-hearts-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/public/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: PostgreSQL database for production-like testing
  postgres:
    image: postgres:15-alpine
    container_name: vietnam-hearts-postgres
    environment:
      POSTGRES_DB: vietnam_hearts
      POSTGRES_USER: vietnam_hearts
      POSTGRES_PASSWORD: vietnam_hearts_dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - vietnam-hearts-network
    restart: unless-stopped
    profiles:
      - database

networks:
  vietnam-hearts-network:
    driver: bridge

volumes:
  postgres_data: 